### ISSUE TITLE
Il log in non funziona

### ISSUE THREAD

**Issue by MicheleGalliano** [supermirtillo/polito-materiale#6]
Stavo proprio cercando uno script che faccia il download del materiale, ma quando ho installato e provato non mi permette di fare il login: dice "Impossibile effettuare il login". Forse ho notato che mettendo la password giusta ci mette di più a dare l'errore mentre quando la metto sbagliata è molto veloce.

**Comment by glumia** [comment]
Ciao Michele! Molto probabilmente è cambiato qualcosa nel codice html delle pagine del polito o il loro flusso di autenticazione e il codice in https://github.com/lucaceriani/polito-materiale/blob/ce4bc00b7cab4b9c126d5b8ef62f31a36116c697/src/polito_web.py#L72 non funziona più. 

Bisognerebbe mettersi con una shell python e provare ad eseguire quelle istruzioni una ad una per vedere cosa è esattamente che si sta rompendo e poi dare un'occhiata alle chiamate http del login su didattica.polito.it con gli strumenti di sviluppo del browser per capire come eventualmente va sistemato il codice.

Avresti voglia di provarci?

**Comment by MicheleGalliano** [comment]
dovrei essere riuscito a risolvere

**Comment by glumia** [comment]
Grande! 

Giusto un appunto, la prossima volta lascia la issue aperta e scrivi `Closes #{numero della issue}` (in questo caso `Closes #6`) nella pull request così la issue viene chiusa in automatico non appena la pr viene mergiata.
